#!/usr/bin/env bash
# Spec: specs/0001-rebrand-product-json/spec.md — Story 2 cenário 2, Critério de Sucesso #7, #8
# Asserts that the NZRCode visual assets (icons, fonts, brand SVG) are present.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

fail=0
require_file() {
  if [ ! -f "$ROOT/$1" ]; then
    echo "FAIL: missing file $1"
    fail=1
  fi
}

# Brand source (single source of truth for raster generation)
require_file 'resources/nzrcode-brand/wordmark.svg'
require_file 'resources/nzrcode-brand/colors.json'

# Pin SVG hash — refreshing the wordmark must be deliberate, not accidental.
# Update this value (and regenerate icons) when the SVG is intentionally changed.
EXPECTED_SVG_SHA='c4938e7de67afc40942272b2b603a8cc67d5f257dcd7332a19fbacc36da99b20'
if [ -f "$ROOT/resources/nzrcode-brand/wordmark.svg" ]; then
  actual=$(sha256sum "$ROOT/resources/nzrcode-brand/wordmark.svg" | awk '{print $1}')
  if [ "$actual" != "$EXPECTED_SVG_SHA" ]; then
    echo "FAIL: wordmark.svg sha256 mismatch — expected $EXPECTED_SVG_SHA, got $actual"
    fail=1
  fi
fi

# Platform icons (generated by build/lib/nzrcode/generate-icons.mjs)
require_file 'resources/darwin/nzrcode.icns'
require_file 'resources/linux/nzrcode.png'
require_file 'resources/win32/nzrcode_70x70.png'
require_file 'resources/win32/nzrcode_150x150.png'

# JetBrains Mono bundle + license
require_file 'resources/fonts/JetBrainsMono-Regular.woff2'
require_file 'resources/fonts/JetBrainsMono-Medium.woff2'
require_file 'resources/fonts/JetBrainsMono-Bold.woff2'
require_file 'resources/fonts/LICENSE-JetBrainsMono.txt'

# Idempotency check: re-running the icon generator must not change bytes
if [ "$fail" -eq 0 ] && [ -f "$ROOT/build/lib/nzrcode/generate-icons.mjs" ]; then
  if ! (cd "$ROOT" && node build/lib/nzrcode/generate-icons.mjs --check >/dev/null 2>&1); then
    echo "FAIL: generate-icons.mjs --check reports drift between SVG source and committed binaries"
    fail=1
  fi
fi

if [ "$fail" -eq 0 ]; then
  echo "PASS: brand assets present and consistent"
fi
exit "$fail"
